use rand::Rng;

pub fn choose_word() -> Vec<char> {
    let words = [
        "apple",
        "banana",
        "cherry",
        "date",
        "elderberry",
        "fig",
        "grape",
        "honeydew",
        "kiwi",
        "lemon",
        "mango",
        "nectarine",
        "orange",
        "peach",
        "quince",
        "raspberry",
        "strawberry",
        "tangerine",
        "watermelon",
        "avocado",
        "broccoli",
        "carrot",
        "cucumber",
        "daikon",
        "eggplant",
        "fennel",
        "garlic",
        "horseradish",
        "jalapeno",
        "kale",
        "lettuce",
        "mushroom",
        "napa",
        "onion",
        "pepper",
        "quinoa",
        "radish",
        "spinach",
        "tomato",
        "udon",
        "vinegar",
        "wakame",
        "xigua",
        "yam",
        "zucchini",
        "almond",
        "cashew",
        "date",
        "elderberry",
        "fig",
        "grapefruit",
        "hazelnut",
        "kiwi",
        "lemon",
        "mango",
        "nectarine",
        "olive",
        "pineapple",
        "quince",
        "raspberry",
        "strawberry",
        "tangerine",
        "watermelon",
        "apricot",
        "blueberry",
        "cranberry",
        "durian",
        "elderflower",
        "fig",
        "grape",
        "honeydew",
        "italian",
        "jicama",
        "kale",
        "leek",
        "mushroom",
        "nutmeg",
        "olive",
        "pea",
        "quinoa",
        "radish",
        "spinach",
        "tomato",
        "udon",
        "vanilla",
        "watercress",
        "xigua",
        "yam",
        "zucchini",
        "almond",
        "banana",
        "cantaloupe",
        "dragonfruit",
        "elderberry",
        "fig",
        "grape",
        "honeydew",
        "iceberg",
    ];

    let num = rand::thread_rng().gen_range(0..97);

    let word = words[num];
    let mut vec_words = Vec::new();

    for ch in word.chars() {
        vec_words.push(ch);
    }

    vec_words
}
